# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
env:
  - CGO_ENABLED=0
builds:
  - targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64
    hooks:
      post:
        - mkdir -p ./dist/raw
        - cp "{{ .Path }}" "./dist/raw/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
  extra_files:
    - glob: ./dist/raw/*
release:
  github:
  draft: true
snapshot:
  version_template: "{{ .Tag }}-dev"
