// This file generated by `generator/main.go`. DO NOT EDIT

package api

import (
	"fmt"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-aws/aws"
)

// AwsALBInvalidSecurityGroupRule checks whether attribute value actually exists
type AwsALBInvalidSecurityGroupRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	data          map[string]bool
	dataPrepared  bool
}

// NewAwsALBInvalidSecurityGroupRule returns new rule with default attributes
func NewAwsALBInvalidSecurityGroupRule() *AwsALBInvalidSecurityGroupRule {
	return &AwsALBInvalidSecurityGroupRule{
		resourceType:  "aws_alb",
		attributeName: "security_groups",
		data:          map[string]bool{},
		dataPrepared:  false,
	}
}

// Name returns the rule name
func (r *AwsALBInvalidSecurityGroupRule) Name() string {
	return "aws_alb_invalid_security_group"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsALBInvalidSecurityGroupRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsALBInvalidSecurityGroupRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsALBInvalidSecurityGroupRule) Link() string {
	return ""
}

// Metadata returns the metadata about deep checking
func (r *AwsALBInvalidSecurityGroupRule) Metadata() interface{} {
	return map[string]bool{"deep": true}
}

// Check checks whether the attributes are included in the list retrieved by DescribeSecurityGroups
func (r *AwsALBInvalidSecurityGroupRule) Check(rr tflint.Runner) error {
	runner := rr.(*aws.Runner)

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		if !r.dataPrepared {
			logger.Debug("invoking DescribeSecurityGroups")
			var err error
			r.data, err = runner.AwsClient.DescribeSecurityGroups()
			if err != nil {
				err := fmt.Errorf("An error occurred while invoking DescribeSecurityGroups; %w", err)
				logger.Error("%s", err)
				return err
			}
			r.dataPrepared = true
		}

		return runner.EachStringSliceExprs(attribute.Expr, func(val string, expr hcl.Expression) {
			if !r.data[val] {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is invalid security group.`, val),
					expr.Range(),
				)
			}
		})
	}

	return nil
}
