// This file generated by `generator/main.go`. DO NOT EDIT

package api

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
	"github.com/terraform-linters/tflint-ruleset-aws/aws"
)

// AwsRouteInvalidVpcPeeringConnectionRule checks whether attribute value actually exists
type AwsRouteInvalidVpcPeeringConnectionRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	data          map[string]bool
	dataPrepared  bool
}

// NewAwsRouteInvalidVpcPeeringConnectionRule returns new rule with default attributes
func NewAwsRouteInvalidVpcPeeringConnectionRule() *AwsRouteInvalidVpcPeeringConnectionRule {
	return &AwsRouteInvalidVpcPeeringConnectionRule{
		resourceType:  "aws_route",
		attributeName: "vpc_peering_connection_id",
		data:          map[string]bool{},
		dataPrepared:  false,
	}
}

// Name returns the rule name
func (r *AwsRouteInvalidVpcPeeringConnectionRule) Name() string {
	return "aws_route_invalid_vpc_peering_connection"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsRouteInvalidVpcPeeringConnectionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsRouteInvalidVpcPeeringConnectionRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsRouteInvalidVpcPeeringConnectionRule) Link() string {
	return ""
}

// Metadata returns the metadata about deep checking
func (r *AwsRouteInvalidVpcPeeringConnectionRule) Metadata() interface{} {
	return map[string]bool{"deep": true}
}

// Check checks whether the attributes are included in the list retrieved by DescribeVpcPeeringConnections
func (r *AwsRouteInvalidVpcPeeringConnectionRule) Check(rr tflint.Runner) error {
	runner := rr.(*aws.Runner)

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
			{Name: "provider"},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		if !r.dataPrepared {
			awsClient, err := runner.AwsClient(resource.Body.Attributes)
			if err != nil {
				return err
			}
			logger.Debug("invoking DescribeVpcPeeringConnections")
			r.data, err = awsClient.DescribeVpcPeeringConnections()
			if err != nil {
				err := fmt.Errorf("An error occurred while invoking DescribeVpcPeeringConnections; %w", err)
				logger.Error("%s", err)
				return err
			}
			r.dataPrepared = true
		}

		err := runner.EvaluateExpr(attribute.Expr, func (val string) error {
			if !r.data[val] {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is invalid VPC peering connection ID.`, val),
					attribute.Expr.Range(),
				)
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
