// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsLightsailStaticIPAttachmentInvalidStaticIPNameRule checks the pattern is valid
type AwsLightsailStaticIPAttachmentInvalidStaticIPNameRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAwsLightsailStaticIPAttachmentInvalidStaticIPNameRule returns new rule with default attributes
func NewAwsLightsailStaticIPAttachmentInvalidStaticIPNameRule() *AwsLightsailStaticIPAttachmentInvalidStaticIPNameRule {
	return &AwsLightsailStaticIPAttachmentInvalidStaticIPNameRule{
		resourceType:  "aws_lightsail_static_ip_attachment",
		attributeName: "static_ip_name",
		pattern:       regexp.MustCompile(`^\w[\w\-]*\w$`),
	}
}

// Name returns the rule name
func (r *AwsLightsailStaticIPAttachmentInvalidStaticIPNameRule) Name() string {
	return "aws_lightsail_static_ip_attachment_invalid_static_ip_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsLightsailStaticIPAttachmentInvalidStaticIPNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsLightsailStaticIPAttachmentInvalidStaticIPNameRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsLightsailStaticIPAttachmentInvalidStaticIPNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsLightsailStaticIPAttachmentInvalidStaticIPNameRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^\w[\w\-]*\w$`),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
