// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsAppconfigConfigurationProfileInvalidLocationURIRule checks the pattern is valid
type AwsAppconfigConfigurationProfileInvalidLocationURIRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsAppconfigConfigurationProfileInvalidLocationURIRule returns new rule with default attributes
func NewAwsAppconfigConfigurationProfileInvalidLocationURIRule() *AwsAppconfigConfigurationProfileInvalidLocationURIRule {
	return &AwsAppconfigConfigurationProfileInvalidLocationURIRule{
		resourceType:  "aws_appconfig_configuration_profile",
		attributeName: "location_uri",
		max:           2048,
		min:           1,
	}
}

// Name returns the rule name
func (r *AwsAppconfigConfigurationProfileInvalidLocationURIRule) Name() string {
	return "aws_appconfig_configuration_profile_invalid_location_uri"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsAppconfigConfigurationProfileInvalidLocationURIRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsAppconfigConfigurationProfileInvalidLocationURIRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsAppconfigConfigurationProfileInvalidLocationURIRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsAppconfigConfigurationProfileInvalidLocationURIRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"location_uri must be 2048 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"location_uri must be 1 characters or higher",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
