// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsCloudwatchLogGroupInvalidNameRule(t *testing.T) {
	cases := []struct {
		Content  string
		Expected helper.Issues
	}{
		{
			Content: `
resource "aws_cloudwatch_log_group" "foo" {
	name = Yada
	}`,
			Expected: helper.Issues{},
		},
		{
			Content: `
resource "aws_cloudwatch_log_group" "foo" {
	name = Yoda:prod
	}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsCloudwatchLogGroupInvalidNameRule(),
					Message: `Yoda:prod does not match valid pattern ^[\.\-_/#A-Za-z0-9]+$`,
				},
			},
		},
	}

	rule := NewAwsCloudwatchLogGroupInvalidNameRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
