// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule checks the pattern is valid
type AwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule returns new rule with default attributes
func NewAwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule() *AwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule {
	return &AwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule{
		resourceType:  "aws_codedeploy_deployment_group",
		attributeName: "deployment_group_name",
		max:           100,
		min:           1,
	}
}

// Name returns the rule name
func (r *AwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule) Name() string {
	return "aws_codedeploy_deployment_group_invalid_deployment_group_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsCodedeployDeploymentGroupInvalidDeploymentGroupNameRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"deployment_group_name must be 100 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"deployment_group_name must be 1 characters or higher",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
