// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsEbsVolumeInvalidTypeRule checks the pattern is valid
type AwsEbsVolumeInvalidTypeRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsEbsVolumeInvalidTypeRule returns new rule with default attributes
func NewAwsEbsVolumeInvalidTypeRule() *AwsEbsVolumeInvalidTypeRule {
	return &AwsEbsVolumeInvalidTypeRule{
		resourceType:  "aws_ebs_volume",
		attributeName: "type",
		enum: []string{
			"standard",
			"io1",
			"io2",
			"gp2",
			"sc1",
			"st1",
			"gp3",
		},
	}
}

// Name returns the rule name
func (r *AwsEbsVolumeInvalidTypeRule) Name() string {
	return "aws_ebs_volume_invalid_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsEbsVolumeInvalidTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsEbsVolumeInvalidTypeRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsEbsVolumeInvalidTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsEbsVolumeInvalidTypeRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as type`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
