// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule(t *testing.T) {
	cases := []struct {
		Name     string
		Content  string
		Expected helper.Issues
	}{
		{
			Name: "It includes invalid characters",
			Content: `
resource "aws_config_config_rule" "foo" {
	maximum_execution_frequency = "Hour"
}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule(),
					Message: fmt.Sprintf(`%q is an invalid value as %s`, truncateLongMessage("Hour"), "maximum_execution_frequency"),
				},
			},
		},
		{
			Name: "It is valid",
			Content: `
resource "aws_config_config_rule" "foo" {
	maximum_execution_frequency = "One_Hour"
}`,
			Expected: helper.Issues{},
		},
	}

	rule := NewAwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
