// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsCloudwatchEventTargetInvalidTargetIDRule(t *testing.T) {
	cases := []struct {
		Content  string
		Expected helper.Issues
	}{
		{
			Content: `
resource "aws_cloudwatch_event_target" "foo" {
	target_id = run-scheduled-task-every-hour
	}`,
			Expected: helper.Issues{},
		},
		{
			Content: `
resource "aws_cloudwatch_event_target" "foo" {
	target_id = run scheduled task every hour
	}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsCloudwatchEventTargetInvalidTargetIDRule(),
					Message: `run scheduled task every hour does not match valid pattern ^[\.\-_A-Za-z0-9]+$`,
				},
			},
		},
	}

	rule := NewAwsCloudwatchEventTargetInvalidTargetIDRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
