// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsLaunchTemplateInvalidInstanceTypeRule(t *testing.T) {
	cases := []struct {
		Content  string
		Expected helper.Issues
	}{
		{
			Content: `
resource "aws_launch_template" "foo" {
	instance_type = t2.micro
	}`,
			Expected: helper.Issues{},
		},
		{
			Content: `
resource "aws_launch_template" "foo" {
	instance_type = t1.2xlarge
	}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsLaunchTemplateInvalidInstanceTypeRule(),
					Message: `t1.2xlarge is an invalid value as instance_type`,
				},
			},
		},
	}

	rule := NewAwsLaunchTemplateInvalidInstanceTypeRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
