// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsBudgetsBudgetInvalidNameRule(t *testing.T) {
	cases := []struct {
		Name     string
		Content  string
		Expected helper.Issues
	}{
		{
			Name: "It includes invalid characters",
			Content: `
resource "aws_budgets_budget" "foo" {
	name = "budget:ec2:monthly"
}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsBudgetsBudgetInvalidNameRule(),
					Message: fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage("budget:ec2:monthly"), `^[^:\\]+$`),
				},
			},
		},
		{
			Name: "It is valid",
			Content: `
resource "aws_budgets_budget" "foo" {
	name = "budget-ec2-monthly"
}`,
			Expected: helper.Issues{},
		},
	}

	rule := NewAwsBudgetsBudgetInvalidNameRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
