// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsEcsTaskSetInvalidLaunchTypeRule checks the pattern is valid
type AwsEcsTaskSetInvalidLaunchTypeRule struct {
	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsEcsTaskSetInvalidLaunchTypeRule returns new rule with default attributes
func NewAwsEcsTaskSetInvalidLaunchTypeRule() *AwsEcsTaskSetInvalidLaunchTypeRule {
	return &AwsEcsTaskSetInvalidLaunchTypeRule{
		resourceType:  "aws_ecs_task_set",
		attributeName: "launch_type",
		enum: []string{
			"EC2",
			"FARGATE",
			"EXTERNAL",
		},
	}
}

// Name returns the rule name
func (r *AwsEcsTaskSetInvalidLaunchTypeRule) Name() string {
	return "aws_ecs_task_set_invalid_launch_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsEcsTaskSetInvalidLaunchTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsEcsTaskSetInvalidLaunchTypeRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsEcsTaskSetInvalidLaunchTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsEcsTaskSetInvalidLaunchTypeRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" is an invalid value as launch_type`, truncateLongMessage(val)),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
