// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsElasticsearchDomainSamlOptionsInvalidDomainNameRule checks the pattern is valid
type AwsElasticsearchDomainSamlOptionsInvalidDomainNameRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
	pattern       *regexp.Regexp
}

// NewAwsElasticsearchDomainSamlOptionsInvalidDomainNameRule returns new rule with default attributes
func NewAwsElasticsearchDomainSamlOptionsInvalidDomainNameRule() *AwsElasticsearchDomainSamlOptionsInvalidDomainNameRule {
	return &AwsElasticsearchDomainSamlOptionsInvalidDomainNameRule{
		resourceType:  "aws_elasticsearch_domain_saml_options",
		attributeName: "domain_name",
		max:           28,
		min:           3,
		pattern:       regexp.MustCompile(`^[a-z][a-z0-9\-]+$`),
	}
}

// Name returns the rule name
func (r *AwsElasticsearchDomainSamlOptionsInvalidDomainNameRule) Name() string {
	return "aws_elasticsearch_domain_saml_options_invalid_domain_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsElasticsearchDomainSamlOptionsInvalidDomainNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsElasticsearchDomainSamlOptionsInvalidDomainNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsElasticsearchDomainSamlOptionsInvalidDomainNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsElasticsearchDomainSamlOptionsInvalidDomainNameRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"domain_name must be 28 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"domain_name must be 3 characters or higher",
					attribute.Expr,
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[a-z][a-z0-9\-]+$`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
