// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsBudgetsBudgetInvalidBudgetTypeRule checks the pattern is valid
type AwsBudgetsBudgetInvalidBudgetTypeRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsBudgetsBudgetInvalidBudgetTypeRule returns new rule with default attributes
func NewAwsBudgetsBudgetInvalidBudgetTypeRule() *AwsBudgetsBudgetInvalidBudgetTypeRule {
	return &AwsBudgetsBudgetInvalidBudgetTypeRule{
		resourceType:  "aws_budgets_budget",
		attributeName: "budget_type",
		enum: []string{
			"USAGE",
			"COST",
			"RI_UTILIZATION",
			"RI_COVERAGE",
			"SAVINGS_PLANS_UTILIZATION",
			"SAVINGS_PLANS_COVERAGE",
		},
	}
}

// Name returns the rule name
func (r *AwsBudgetsBudgetInvalidBudgetTypeRule) Name() string {
	return "aws_budgets_budget_invalid_budget_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsBudgetsBudgetInvalidBudgetTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsBudgetsBudgetInvalidBudgetTypeRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsBudgetsBudgetInvalidBudgetTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsBudgetsBudgetInvalidBudgetTypeRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as budget_type`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
