// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsGlueResourcePolicyInvalidEnableHybridRule checks the pattern is valid
type AwsGlueResourcePolicyInvalidEnableHybridRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsGlueResourcePolicyInvalidEnableHybridRule returns new rule with default attributes
func NewAwsGlueResourcePolicyInvalidEnableHybridRule() *AwsGlueResourcePolicyInvalidEnableHybridRule {
	return &AwsGlueResourcePolicyInvalidEnableHybridRule{
		resourceType:  "aws_glue_resource_policy",
		attributeName: "enable_hybrid",
		enum: []string{
			"TRUE",
			"FALSE",
		},
	}
}

// Name returns the rule name
func (r *AwsGlueResourcePolicyInvalidEnableHybridRule) Name() string {
	return "aws_glue_resource_policy_invalid_enable_hybrid"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsGlueResourcePolicyInvalidEnableHybridRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsGlueResourcePolicyInvalidEnableHybridRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsGlueResourcePolicyInvalidEnableHybridRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsGlueResourcePolicyInvalidEnableHybridRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as enable_hybrid`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
