// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsSsoadminPermissionSetInvalidInstanceArnRule checks the pattern is valid
type AwsSsoadminPermissionSetInvalidInstanceArnRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
	pattern       *regexp.Regexp
}

// NewAwsSsoadminPermissionSetInvalidInstanceArnRule returns new rule with default attributes
func NewAwsSsoadminPermissionSetInvalidInstanceArnRule() *AwsSsoadminPermissionSetInvalidInstanceArnRule {
	return &AwsSsoadminPermissionSetInvalidInstanceArnRule{
		resourceType:  "aws_ssoadmin_permission_set",
		attributeName: "instance_arn",
		max:           1224,
		min:           10,
		pattern:       regexp.MustCompile(`^arn:aws:sso:::instance/(sso)?ins-[a-zA-Z0-9-.]{16}$`),
	}
}

// Name returns the rule name
func (r *AwsSsoadminPermissionSetInvalidInstanceArnRule) Name() string {
	return "aws_ssoadmin_permission_set_invalid_instance_arn"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsSsoadminPermissionSetInvalidInstanceArnRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsSsoadminPermissionSetInvalidInstanceArnRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsSsoadminPermissionSetInvalidInstanceArnRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsSsoadminPermissionSetInvalidInstanceArnRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"instance_arn must be 1224 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"instance_arn must be 10 characters or higher",
					attribute.Expr,
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^arn:aws:sso:::instance/(sso)?ins-[a-zA-Z0-9-.]{16}$`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
