// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsSecurityhubActionTargetInvalidNameRule checks the pattern is valid
type AwsSecurityhubActionTargetInvalidNameRule struct {
	resourceType  string
	attributeName string
	pattern       *regexp.Regexp
}

// NewAwsSecurityhubActionTargetInvalidNameRule returns new rule with default attributes
func NewAwsSecurityhubActionTargetInvalidNameRule() *AwsSecurityhubActionTargetInvalidNameRule {
	return &AwsSecurityhubActionTargetInvalidNameRule{
		resourceType:  "aws_securityhub_action_target",
		attributeName: "name",
		pattern:       regexp.MustCompile(`^.*\S.*$`),
	}
}

// Name returns the rule name
func (r *AwsSecurityhubActionTargetInvalidNameRule) Name() string {
	return "aws_securityhub_action_target_invalid_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsSecurityhubActionTargetInvalidNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsSecurityhubActionTargetInvalidNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsSecurityhubActionTargetInvalidNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsSecurityhubActionTargetInvalidNameRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^.*\S.*$`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
