// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsGlueCatalogTableInvalidViewExpandedTextRule checks the pattern is valid
type AwsGlueCatalogTableInvalidViewExpandedTextRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	max           int
}

// NewAwsGlueCatalogTableInvalidViewExpandedTextRule returns new rule with default attributes
func NewAwsGlueCatalogTableInvalidViewExpandedTextRule() *AwsGlueCatalogTableInvalidViewExpandedTextRule {
	return &AwsGlueCatalogTableInvalidViewExpandedTextRule{
		resourceType:  "aws_glue_catalog_table",
		attributeName: "view_expanded_text",
		max:           409600,
	}
}

// Name returns the rule name
func (r *AwsGlueCatalogTableInvalidViewExpandedTextRule) Name() string {
	return "aws_glue_catalog_table_invalid_view_expanded_text"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsGlueCatalogTableInvalidViewExpandedTextRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsGlueCatalogTableInvalidViewExpandedTextRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsGlueCatalogTableInvalidViewExpandedTextRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsGlueCatalogTableInvalidViewExpandedTextRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func (val string) error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"view_expanded_text must be 409600 characters or less",
					attribute.Expr.Range(),
				)
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
