// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule checks the pattern is valid
type AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule returns new rule with default attributes
func NewAwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule() *AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule {
	return &AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule{
		resourceType:  "aws_config_config_rule",
		attributeName: "maximum_execution_frequency",
		enum: []string{
			"One_Hour",
			"Three_Hours",
			"Six_Hours",
			"Twelve_Hours",
			"TwentyFour_Hours",
		},
	}
}

// Name returns the rule name
func (r *AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule) Name() string {
	return "aws_config_config_rule_invalid_maximum_execution_frequency"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsConfigConfigRuleInvalidMaximumExecutionFrequencyRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as maximum_execution_frequency`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
