// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsServicecatalogConstraintInvalidAcceptLanguageRule checks the pattern is valid
type AwsServicecatalogConstraintInvalidAcceptLanguageRule struct {
	resourceType  string
	attributeName string
	max           int
}

// NewAwsServicecatalogConstraintInvalidAcceptLanguageRule returns new rule with default attributes
func NewAwsServicecatalogConstraintInvalidAcceptLanguageRule() *AwsServicecatalogConstraintInvalidAcceptLanguageRule {
	return &AwsServicecatalogConstraintInvalidAcceptLanguageRule{
		resourceType:  "aws_servicecatalog_constraint",
		attributeName: "accept_language",
		max:           100,
	}
}

// Name returns the rule name
func (r *AwsServicecatalogConstraintInvalidAcceptLanguageRule) Name() string {
	return "aws_servicecatalog_constraint_invalid_accept_language"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsServicecatalogConstraintInvalidAcceptLanguageRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsServicecatalogConstraintInvalidAcceptLanguageRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsServicecatalogConstraintInvalidAcceptLanguageRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsServicecatalogConstraintInvalidAcceptLanguageRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"accept_language must be 100 characters or less",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
