// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsSsmPatchBaselineInvalidOperatingSystemRule checks the pattern is valid
type AwsSsmPatchBaselineInvalidOperatingSystemRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsSsmPatchBaselineInvalidOperatingSystemRule returns new rule with default attributes
func NewAwsSsmPatchBaselineInvalidOperatingSystemRule() *AwsSsmPatchBaselineInvalidOperatingSystemRule {
	return &AwsSsmPatchBaselineInvalidOperatingSystemRule{
		resourceType:  "aws_ssm_patch_baseline",
		attributeName: "operating_system",
		enum: []string{
			"WINDOWS",
			"AMAZON_LINUX",
			"AMAZON_LINUX_2",
			"UBUNTU",
			"REDHAT_ENTERPRISE_LINUX",
			"SUSE",
			"CENTOS",
			"ORACLE_LINUX",
			"DEBIAN",
			"MACOS",
			"RASPBIAN",
		},
	}
}

// Name returns the rule name
func (r *AwsSsmPatchBaselineInvalidOperatingSystemRule) Name() string {
	return "aws_ssm_patch_baseline_invalid_operating_system"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsSsmPatchBaselineInvalidOperatingSystemRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsSsmPatchBaselineInvalidOperatingSystemRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsSsmPatchBaselineInvalidOperatingSystemRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsSsmPatchBaselineInvalidOperatingSystemRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as operating_system`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
