// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsApprunnerConnectionInvalidConnectionNameRule checks the pattern is valid
type AwsApprunnerConnectionInvalidConnectionNameRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
	pattern       *regexp.Regexp
}

// NewAwsApprunnerConnectionInvalidConnectionNameRule returns new rule with default attributes
func NewAwsApprunnerConnectionInvalidConnectionNameRule() *AwsApprunnerConnectionInvalidConnectionNameRule {
	return &AwsApprunnerConnectionInvalidConnectionNameRule{
		resourceType:  "aws_apprunner_connection",
		attributeName: "connection_name",
		max:           32,
		min:           4,
		pattern:       regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9\-_]{3,31}$`),
	}
}

// Name returns the rule name
func (r *AwsApprunnerConnectionInvalidConnectionNameRule) Name() string {
	return "aws_apprunner_connection_invalid_connection_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsApprunnerConnectionInvalidConnectionNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsApprunnerConnectionInvalidConnectionNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsApprunnerConnectionInvalidConnectionNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsApprunnerConnectionInvalidConnectionNameRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"connection_name must be 32 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"connection_name must be 4 characters or higher",
					attribute.Expr,
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[A-Za-z0-9][A-Za-z0-9\-_]{3,31}$`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
