// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsGuarddutyPublishingDestinationInvalidDestinationTypeRule checks the pattern is valid
type AwsGuarddutyPublishingDestinationInvalidDestinationTypeRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	max           int
	min           int
	enum          []string
}

// NewAwsGuarddutyPublishingDestinationInvalidDestinationTypeRule returns new rule with default attributes
func NewAwsGuarddutyPublishingDestinationInvalidDestinationTypeRule() *AwsGuarddutyPublishingDestinationInvalidDestinationTypeRule {
	return &AwsGuarddutyPublishingDestinationInvalidDestinationTypeRule{
		resourceType:  "aws_guardduty_publishing_destination",
		attributeName: "destination_type",
		max:           300,
		min:           1,
		enum: []string{
			"S3",
		},
	}
}

// Name returns the rule name
func (r *AwsGuarddutyPublishingDestinationInvalidDestinationTypeRule) Name() string {
	return "aws_guardduty_publishing_destination_invalid_destination_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsGuarddutyPublishingDestinationInvalidDestinationTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsGuarddutyPublishingDestinationInvalidDestinationTypeRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsGuarddutyPublishingDestinationInvalidDestinationTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsGuarddutyPublishingDestinationInvalidDestinationTypeRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"destination_type must be 300 characters or less",
					attribute.Expr.Range(),
				)
			}
			if len(val) < r.min {
				runner.EmitIssue(
					r,
					"destination_type must be 1 characters or higher",
					attribute.Expr.Range(),
				)
			}
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as destination_type`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
