// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsLbTargetGroupInvalidTargetTypeRule(t *testing.T) {
	cases := []struct {
		Content  string
		Expected helper.Issues
	}{
		{
			Content: `
resource "aws_lb_target_group" "foo" {
	target_type = lambda
	}`,
			Expected: helper.Issues{},
		},
		{
			Content: `
resource "aws_lb_target_group" "foo" {
	target_type = container
	}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsLbTargetGroupInvalidTargetTypeRule(),
					Message: `container is an invalid value as target_type`,
				},
			},
		},
	}

	rule := NewAwsLbTargetGroupInvalidTargetTypeRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
