// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsCodeartifactRepositoryInvalidDomainRule checks the pattern is valid
type AwsCodeartifactRepositoryInvalidDomainRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
	pattern       *regexp.Regexp
}

// NewAwsCodeartifactRepositoryInvalidDomainRule returns new rule with default attributes
func NewAwsCodeartifactRepositoryInvalidDomainRule() *AwsCodeartifactRepositoryInvalidDomainRule {
	return &AwsCodeartifactRepositoryInvalidDomainRule{
		resourceType:  "aws_codeartifact_repository",
		attributeName: "domain",
		max:           50,
		min:           2,
		pattern:       regexp.MustCompile(`^[a-z][a-z0-9\-]{0,48}[a-z0-9]$`),
	}
}

// Name returns the rule name
func (r *AwsCodeartifactRepositoryInvalidDomainRule) Name() string {
	return "aws_codeartifact_repository_invalid_domain"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsCodeartifactRepositoryInvalidDomainRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsCodeartifactRepositoryInvalidDomainRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsCodeartifactRepositoryInvalidDomainRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsCodeartifactRepositoryInvalidDomainRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"domain must be 50 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"domain must be 2 characters or higher",
					attribute.Expr,
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[a-z][a-z0-9\-]{0,48}[a-z0-9]$`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
