// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsCloudwatchMetricAlarmInvalidNamespaceRule(t *testing.T) {
	cases := []struct {
		Name     string
		Content  string
		Expected helper.Issues
	}{
		{
			Name: "It includes invalid characters",
			Content: `
resource "aws_cloudwatch_metric_alarm" "foo" {
	namespace = ":EC2"
}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsCloudwatchMetricAlarmInvalidNamespaceRule(),
					Message: fmt.Sprintf(`%q does not match valid pattern %s`, truncateLongMessage(":EC2"), `^[^:].*$`),
				},
			},
		},
		{
			Name: "It is valid",
			Content: `
resource "aws_cloudwatch_metric_alarm" "foo" {
	namespace = "AWS/EC2"
}`,
			Expected: helper.Issues{},
		},
	}

	rule := NewAwsCloudwatchMetricAlarmInvalidNamespaceRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
