// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"regexp"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule checks the pattern is valid
type AwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	max           int
	min           int
	pattern       *regexp.Regexp
}

// NewAwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule returns new rule with default attributes
func NewAwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule() *AwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule {
	return &AwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule{
		resourceType:  "aws_ssoadmin_managed_policy_attachment",
		attributeName: "managed_policy_arn",
		max:           2048,
		min:           20,
		pattern:       regexp.MustCompile(`^arn:aws(-[a-z]{1,5}){0,3}:iam::aws:policy((/[A-Za-z0-9\.,\+@=_-]+)*)/([A-Za-z0-9\.,\+=@_-]+)$`),
	}
}

// Name returns the rule name
func (r *AwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule) Name() string {
	return "aws_ssoadmin_managed_policy_attachment_invalid_managed_policy_arn"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsSsoadminManagedPolicyAttachmentInvalidManagedPolicyArnRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func (val string) error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"managed_policy_arn must be 2048 characters or less",
					attribute.Expr.Range(),
				)
			}
			if len(val) < r.min {
				runner.EmitIssue(
					r,
					"managed_policy_arn must be 20 characters or higher",
					attribute.Expr.Range(),
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^arn:aws(-[a-z]{1,5}){0,3}:iam::aws:policy((/[A-Za-z0-9\.,\+@=_-]+)*)/([A-Za-z0-9\.,\+=@_-]+)$`),
					attribute.Expr.Range(),
				)
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
