// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsDirectoryServiceConditionalForwarderInvalidDirectoryIDRule(t *testing.T) {
	cases := []struct {
		Content  string
		Expected helper.Issues
	}{
		{
			Content: `
resource "aws_directory_service_conditional_forwarder" "foo" {
	directory_id = d-1234567890
	}`,
			Expected: helper.Issues{},
		},
		{
			Content: `
resource "aws_directory_service_conditional_forwarder" "foo" {
	directory_id = 1234567890
	}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsDirectoryServiceConditionalForwarderInvalidDirectoryIDRule(),
					Message: `1234567890 does not match valid pattern ^d-[0-9a-f]{10}$`,
				},
			},
		},
	}

	rule := NewAwsDirectoryServiceConditionalForwarderInvalidDirectoryIDRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
