// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsRoute53RecordInvalidAliasRule checks the pattern is valid
type AwsRoute53RecordInvalidAliasRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	keyMax        int
	valueMax      int
}

// NewAwsRoute53RecordInvalidAliasRule returns new rule with default attributes
func NewAwsRoute53RecordInvalidAliasRule() *AwsRoute53RecordInvalidAliasRule {
	return &AwsRoute53RecordInvalidAliasRule{
		resourceType:  "aws_route53_record",
		attributeName: "alias",
		keyMax:        1024,
		valueMax:      32,
	}
}

// Name returns the rule name
func (r *AwsRoute53RecordInvalidAliasRule) Name() string {
	return "aws_route53_record_invalid_alias"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsRoute53RecordInvalidAliasRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsRoute53RecordInvalidAliasRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsRoute53RecordInvalidAliasRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsRoute53RecordInvalidAliasRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val map[string]string) error {
			for k, v := range val {
				if len(k) > r.keyMax {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag key %q must be 1024 characters or less", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
				if len(v) > r.valueMax {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag value for key %q must be 32 characters or less", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
