// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsAPIGatewayIntegrationInvalidTypeRule(t *testing.T) {
	cases := []struct {
		Content  string
		Expected helper.Issues
	}{
		{
			Content: `
resource "aws_api_gateway_integration" "foo" {
	type = HTTP
	}`,
			Expected: helper.Issues{},
		},
		{
			Content: `
resource "aws_api_gateway_integration" "foo" {
	type = AWS_HTTP
	}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsAPIGatewayIntegrationInvalidTypeRule(),
					Message: `AWS_HTTP is an invalid value as type`,
				},
			},
		},
	}

	rule := NewAwsAPIGatewayIntegrationInvalidTypeRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
