// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsDatasyncTaskInvalidCloudwatchLogGroupArnRule checks the pattern is valid
type AwsDatasyncTaskInvalidCloudwatchLogGroupArnRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	max           int
	pattern       *regexp.Regexp
}

// NewAwsDatasyncTaskInvalidCloudwatchLogGroupArnRule returns new rule with default attributes
func NewAwsDatasyncTaskInvalidCloudwatchLogGroupArnRule() *AwsDatasyncTaskInvalidCloudwatchLogGroupArnRule {
	return &AwsDatasyncTaskInvalidCloudwatchLogGroupArnRule{
		resourceType:  "aws_datasync_task",
		attributeName: "cloudwatch_log_group_arn",
		max:           562,
		pattern:       regexp.MustCompile(`^arn:(aws|aws-cn|aws-us-gov|aws-iso|aws-iso-b):logs:[a-z\-0-9]*:[0-9]{12}:log-group:([^:\*]*)(:\*)?$`),
	}
}

// Name returns the rule name
func (r *AwsDatasyncTaskInvalidCloudwatchLogGroupArnRule) Name() string {
	return "aws_datasync_task_invalid_cloudwatch_log_group_arn"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsDatasyncTaskInvalidCloudwatchLogGroupArnRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsDatasyncTaskInvalidCloudwatchLogGroupArnRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsDatasyncTaskInvalidCloudwatchLogGroupArnRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsDatasyncTaskInvalidCloudwatchLogGroupArnRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"cloudwatch_log_group_arn must be 562 characters or less",
					attribute.Expr.Range(),
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^arn:(aws|aws-cn|aws-us-gov|aws-iso|aws-iso-b):logs:[a-z\-0-9]*:[0-9]{12}:log-group:([^:\*]*)(:\*)?$`),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
