// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsCloudformationStackSetInvalidExecutionRoleNameRule(t *testing.T) {
	cases := []struct {
		Name     string
		Content  string
		Expected helper.Issues
	}{
		{
			Name: "It includes invalid characters",
			Content: `
resource "aws_cloudformation_stack_set" "foo" {
	execution_role_name = "AWSCloudFormation/StackSet/ExecutionRole"
}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsCloudformationStackSetInvalidExecutionRoleNameRule(),
					Message: fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage("AWSCloudFormation/StackSet/ExecutionRole"), `^[a-zA-Z_0-9+=,.@-]+$`),
				},
			},
		},
		{
			Name: "It is valid",
			Content: `
resource "aws_cloudformation_stack_set" "foo" {
	execution_role_name = "AWSCloudFormationStackSetExecutionRole"
}`,
			Expected: helper.Issues{},
		},
	}

	rule := NewAwsCloudformationStackSetInvalidExecutionRoleNameRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
