// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsXraySamplingRuleInvalidAttributesRule checks the pattern is valid
type AwsXraySamplingRuleInvalidAttributesRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	keyMax        int
	keyMin        int
	valueMax      int
	valueMin      int
}

// NewAwsXraySamplingRuleInvalidAttributesRule returns new rule with default attributes
func NewAwsXraySamplingRuleInvalidAttributesRule() *AwsXraySamplingRuleInvalidAttributesRule {
	return &AwsXraySamplingRuleInvalidAttributesRule{
		resourceType:  "aws_xray_sampling_rule",
		attributeName: "attributes",
		keyMax:        32,
		keyMin:        1,
		valueMax:      32,
		valueMin:      1,
	}
}

// Name returns the rule name
func (r *AwsXraySamplingRuleInvalidAttributesRule) Name() string {
	return "aws_xray_sampling_rule_invalid_attributes"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsXraySamplingRuleInvalidAttributesRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsXraySamplingRuleInvalidAttributesRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsXraySamplingRuleInvalidAttributesRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsXraySamplingRuleInvalidAttributesRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val map[string]string) error {
			for k, v := range val {
				if len(k) > r.keyMax {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag key %q must be 32 characters or less", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
				if len(k) < r.keyMin {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag key %q must be 1 characters or higher", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
				if len(v) > r.valueMax {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag value for key %q must be 32 characters or less", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
				if len(v) < r.valueMin {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag value for key %q must be 1 characters or higher", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
