// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsLaunchConfigurationInvalidSpotPriceRule checks the pattern is valid
type AwsLaunchConfigurationInvalidSpotPriceRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsLaunchConfigurationInvalidSpotPriceRule returns new rule with default attributes
func NewAwsLaunchConfigurationInvalidSpotPriceRule() *AwsLaunchConfigurationInvalidSpotPriceRule {
	return &AwsLaunchConfigurationInvalidSpotPriceRule{
		resourceType:  "aws_launch_configuration",
		attributeName: "spot_price",
		max:           255,
		min:           1,
	}
}

// Name returns the rule name
func (r *AwsLaunchConfigurationInvalidSpotPriceRule) Name() string {
	return "aws_launch_configuration_invalid_spot_price"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsLaunchConfigurationInvalidSpotPriceRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsLaunchConfigurationInvalidSpotPriceRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsLaunchConfigurationInvalidSpotPriceRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsLaunchConfigurationInvalidSpotPriceRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"spot_price must be 255 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"spot_price must be 1 characters or higher",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
