// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsConnectBotAssociationInvalidLexBotRule checks the pattern is valid
type AwsConnectBotAssociationInvalidLexBotRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	keyMax        int
	valueMax      int
}

// NewAwsConnectBotAssociationInvalidLexBotRule returns new rule with default attributes
func NewAwsConnectBotAssociationInvalidLexBotRule() *AwsConnectBotAssociationInvalidLexBotRule {
	return &AwsConnectBotAssociationInvalidLexBotRule{
		resourceType:  "aws_connect_bot_association",
		attributeName: "lex_bot",
		keyMax:        60,
		valueMax:      50,
	}
}

// Name returns the rule name
func (r *AwsConnectBotAssociationInvalidLexBotRule) Name() string {
	return "aws_connect_bot_association_invalid_lex_bot"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsConnectBotAssociationInvalidLexBotRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsConnectBotAssociationInvalidLexBotRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsConnectBotAssociationInvalidLexBotRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsConnectBotAssociationInvalidLexBotRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val map[string]string) error {
			for k, v := range val {
				if len(k) > r.keyMax {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag key %q must be 60 characters or less", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
				if len(v) > r.valueMax {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag value for key %q must be 50 characters or less", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
