// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsShieldProtectionInvalidNameRule checks the pattern is valid
type AwsShieldProtectionInvalidNameRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
	pattern       *regexp.Regexp
}

// NewAwsShieldProtectionInvalidNameRule returns new rule with default attributes
func NewAwsShieldProtectionInvalidNameRule() *AwsShieldProtectionInvalidNameRule {
	return &AwsShieldProtectionInvalidNameRule{
		resourceType:  "aws_shield_protection",
		attributeName: "name",
		max:           128,
		min:           1,
		pattern:       regexp.MustCompile(`^[ a-zA-Z0-9_\\.\\-]*$`),
	}
}

// Name returns the rule name
func (r *AwsShieldProtectionInvalidNameRule) Name() string {
	return "aws_shield_protection_invalid_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsShieldProtectionInvalidNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsShieldProtectionInvalidNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsShieldProtectionInvalidNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsShieldProtectionInvalidNameRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"name must be 128 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"name must be 1 characters or higher",
					attribute.Expr,
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[ a-zA-Z0-9_\\.\\-]*$`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
