// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsRedshiftClusterInvalidAvailabilityZoneRule checks the pattern is valid
type AwsRedshiftClusterInvalidAvailabilityZoneRule struct {
	resourceType  string
	attributeName string
	max           int
}

// NewAwsRedshiftClusterInvalidAvailabilityZoneRule returns new rule with default attributes
func NewAwsRedshiftClusterInvalidAvailabilityZoneRule() *AwsRedshiftClusterInvalidAvailabilityZoneRule {
	return &AwsRedshiftClusterInvalidAvailabilityZoneRule{
		resourceType:  "aws_redshift_cluster",
		attributeName: "availability_zone",
		max:           2147483647,
	}
}

// Name returns the rule name
func (r *AwsRedshiftClusterInvalidAvailabilityZoneRule) Name() string {
	return "aws_redshift_cluster_invalid_availability_zone"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsRedshiftClusterInvalidAvailabilityZoneRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsRedshiftClusterInvalidAvailabilityZoneRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsRedshiftClusterInvalidAvailabilityZoneRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsRedshiftClusterInvalidAvailabilityZoneRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"availability_zone must be 2147483647 characters or less",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
