// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsGuarddutyFilterInvalidNameRule checks the pattern is valid
type AwsGuarddutyFilterInvalidNameRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsGuarddutyFilterInvalidNameRule returns new rule with default attributes
func NewAwsGuarddutyFilterInvalidNameRule() *AwsGuarddutyFilterInvalidNameRule {
	return &AwsGuarddutyFilterInvalidNameRule{
		resourceType:  "aws_guardduty_filter",
		attributeName: "name",
		max:           64,
		min:           3,
	}
}

// Name returns the rule name
func (r *AwsGuarddutyFilterInvalidNameRule) Name() string {
	return "aws_guardduty_filter_invalid_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsGuarddutyFilterInvalidNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsGuarddutyFilterInvalidNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsGuarddutyFilterInvalidNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsGuarddutyFilterInvalidNameRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"name must be 64 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"name must be 3 characters or higher",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
