// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsCognitoResourceServerInvalidNameRule(t *testing.T) {
	cases := []struct {
		Content  string
		Expected helper.Issues
	}{
		{
			Content: `
resource "aws_cognito_resource_server" "foo" {
	name = example
	}`,
			Expected: helper.Issues{},
		},
		{
			Content: `
resource "aws_cognito_resource_server" "foo" {
	name = example/server
	}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsCognitoResourceServerInvalidNameRule(),
					Message: `example/server does not match valid pattern ^[\w\s+=,.@-]+$`,
				},
			},
		},
	}

	rule := NewAwsCognitoResourceServerInvalidNameRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
