// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsAppconfigEnvironmentInvalidNameRule checks the pattern is valid
type AwsAppconfigEnvironmentInvalidNameRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsAppconfigEnvironmentInvalidNameRule returns new rule with default attributes
func NewAwsAppconfigEnvironmentInvalidNameRule() *AwsAppconfigEnvironmentInvalidNameRule {
	return &AwsAppconfigEnvironmentInvalidNameRule{
		resourceType:  "aws_appconfig_environment",
		attributeName: "name",
		max:           64,
		min:           1,
	}
}

// Name returns the rule name
func (r *AwsAppconfigEnvironmentInvalidNameRule) Name() string {
	return "aws_appconfig_environment_invalid_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsAppconfigEnvironmentInvalidNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsAppconfigEnvironmentInvalidNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsAppconfigEnvironmentInvalidNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsAppconfigEnvironmentInvalidNameRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"name must be 64 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"name must be 1 characters or higher",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
