// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsRedshiftParameterGroupInvalidDescriptionRule checks the pattern is valid
type AwsRedshiftParameterGroupInvalidDescriptionRule struct {
	resourceType  string
	attributeName string
	max           int
}

// NewAwsRedshiftParameterGroupInvalidDescriptionRule returns new rule with default attributes
func NewAwsRedshiftParameterGroupInvalidDescriptionRule() *AwsRedshiftParameterGroupInvalidDescriptionRule {
	return &AwsRedshiftParameterGroupInvalidDescriptionRule{
		resourceType:  "aws_redshift_parameter_group",
		attributeName: "description",
		max:           2147483647,
	}
}

// Name returns the rule name
func (r *AwsRedshiftParameterGroupInvalidDescriptionRule) Name() string {
	return "aws_redshift_parameter_group_invalid_description"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsRedshiftParameterGroupInvalidDescriptionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsRedshiftParameterGroupInvalidDescriptionRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsRedshiftParameterGroupInvalidDescriptionRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsRedshiftParameterGroupInvalidDescriptionRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"description must be 2147483647 characters or less",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
