// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsChimeVoiceConnectorInvalidAwsRegionRule checks the pattern is valid
type AwsChimeVoiceConnectorInvalidAwsRegionRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsChimeVoiceConnectorInvalidAwsRegionRule returns new rule with default attributes
func NewAwsChimeVoiceConnectorInvalidAwsRegionRule() *AwsChimeVoiceConnectorInvalidAwsRegionRule {
	return &AwsChimeVoiceConnectorInvalidAwsRegionRule{
		resourceType:  "aws_chime_voice_connector",
		attributeName: "aws_region",
		enum: []string{
			"us-east-1",
			"us-west-2",
		},
	}
}

// Name returns the rule name
func (r *AwsChimeVoiceConnectorInvalidAwsRegionRule) Name() string {
	return "aws_chime_voice_connector_invalid_aws_region"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsChimeVoiceConnectorInvalidAwsRegionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsChimeVoiceConnectorInvalidAwsRegionRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsChimeVoiceConnectorInvalidAwsRegionRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsChimeVoiceConnectorInvalidAwsRegionRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as aws_region`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
