// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsServicecatalogProductInvalidDistributorRule checks the pattern is valid
type AwsServicecatalogProductInvalidDistributorRule struct {
	resourceType  string
	attributeName string
	max           int
}

// NewAwsServicecatalogProductInvalidDistributorRule returns new rule with default attributes
func NewAwsServicecatalogProductInvalidDistributorRule() *AwsServicecatalogProductInvalidDistributorRule {
	return &AwsServicecatalogProductInvalidDistributorRule{
		resourceType:  "aws_servicecatalog_product",
		attributeName: "distributor",
		max:           8191,
	}
}

// Name returns the rule name
func (r *AwsServicecatalogProductInvalidDistributorRule) Name() string {
	return "aws_servicecatalog_product_invalid_distributor"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsServicecatalogProductInvalidDistributorRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsServicecatalogProductInvalidDistributorRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsServicecatalogProductInvalidDistributorRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsServicecatalogProductInvalidDistributorRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"distributor must be 8191 characters or less",
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
