// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsSagemakerWorkteamInvalidWorkteamNameRule checks the pattern is valid
type AwsSagemakerWorkteamInvalidWorkteamNameRule struct {
	resourceType  string
	attributeName string
	max           int
	min           int
	pattern       *regexp.Regexp
}

// NewAwsSagemakerWorkteamInvalidWorkteamNameRule returns new rule with default attributes
func NewAwsSagemakerWorkteamInvalidWorkteamNameRule() *AwsSagemakerWorkteamInvalidWorkteamNameRule {
	return &AwsSagemakerWorkteamInvalidWorkteamNameRule{
		resourceType:  "aws_sagemaker_workteam",
		attributeName: "workteam_name",
		max:           63,
		min:           1,
		pattern:       regexp.MustCompile(`^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}`),
	}
}

// Name returns the rule name
func (r *AwsSagemakerWorkteamInvalidWorkteamNameRule) Name() string {
	return "aws_sagemaker_workteam_invalid_workteam_name"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsSagemakerWorkteamInvalidWorkteamNameRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsSagemakerWorkteamInvalidWorkteamNameRule) Severity() string {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsSagemakerWorkteamInvalidWorkteamNameRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsSagemakerWorkteamInvalidWorkteamNameRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	return runner.WalkResourceAttributes(r.resourceType, r.attributeName, func(attribute *hcl.Attribute) error {
		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		return runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssueOnExpr(
					r,
					"workteam_name must be 63 characters or less",
					attribute.Expr,
				)
			}
			if len(val) < r.min {
				runner.EmitIssueOnExpr(
					r,
					"workteam_name must be 1 characters or higher",
					attribute.Expr,
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssueOnExpr(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}`),
					attribute.Expr,
				)
			}
			return nil
		})
	})
}
