// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsConfigAggregateAuthorizationInvalidAccountIDRule(t *testing.T) {
	cases := []struct {
		Content  string
		Expected helper.Issues
	}{
		{
			Content: `
resource "aws_config_aggregate_authorization" "foo" {
	account_id = 012345678910
	}`,
			Expected: helper.Issues{},
		},
		{
			Content: `
resource "aws_config_aggregate_authorization" "foo" {
	account_id = 01234567891
	}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsConfigAggregateAuthorizationInvalidAccountIDRule(),
					Message: `01234567891 does not match valid pattern ^\d{12}$`,
				},
			},
		},
	}

	rule := NewAwsConfigAggregateAuthorizationInvalidAccountIDRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
