// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsMqBrokerInvalidDeploymentModeRule checks the pattern is valid
type AwsMqBrokerInvalidDeploymentModeRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsMqBrokerInvalidDeploymentModeRule returns new rule with default attributes
func NewAwsMqBrokerInvalidDeploymentModeRule() *AwsMqBrokerInvalidDeploymentModeRule {
	return &AwsMqBrokerInvalidDeploymentModeRule{
		resourceType:  "aws_mq_broker",
		attributeName: "deployment_mode",
		enum: []string{
			"ACTIVE_STANDBY_MULTI_AZ",
			"CLUSTER_MULTI_AZ",
			"SINGLE_INSTANCE",
		},
	}
}

// Name returns the rule name
func (r *AwsMqBrokerInvalidDeploymentModeRule) Name() string {
	return "aws_mq_broker_invalid_deployment_mode"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsMqBrokerInvalidDeploymentModeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsMqBrokerInvalidDeploymentModeRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsMqBrokerInvalidDeploymentModeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsMqBrokerInvalidDeploymentModeRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func (val string) error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as deployment_mode`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
