// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsApigatewayv2RouteInvalidAuthorizationTypeRule checks the pattern is valid
type AwsApigatewayv2RouteInvalidAuthorizationTypeRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsApigatewayv2RouteInvalidAuthorizationTypeRule returns new rule with default attributes
func NewAwsApigatewayv2RouteInvalidAuthorizationTypeRule() *AwsApigatewayv2RouteInvalidAuthorizationTypeRule {
	return &AwsApigatewayv2RouteInvalidAuthorizationTypeRule{
		resourceType:  "aws_apigatewayv2_route",
		attributeName: "authorization_type",
		enum: []string{
			"NONE",
			"AWS_IAM",
			"CUSTOM",
			"JWT",
		},
	}
}

// Name returns the rule name
func (r *AwsApigatewayv2RouteInvalidAuthorizationTypeRule) Name() string {
	return "aws_apigatewayv2_route_invalid_authorization_type"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsApigatewayv2RouteInvalidAuthorizationTypeRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsApigatewayv2RouteInvalidAuthorizationTypeRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsApigatewayv2RouteInvalidAuthorizationTypeRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsApigatewayv2RouteInvalidAuthorizationTypeRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as authorization_type`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
