// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsS3BucketInvalidAccelerationStatusRule checks the pattern is valid
type AwsS3BucketInvalidAccelerationStatusRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	enum          []string
}

// NewAwsS3BucketInvalidAccelerationStatusRule returns new rule with default attributes
func NewAwsS3BucketInvalidAccelerationStatusRule() *AwsS3BucketInvalidAccelerationStatusRule {
	return &AwsS3BucketInvalidAccelerationStatusRule{
		resourceType:  "aws_s3_bucket",
		attributeName: "acceleration_status",
		enum: []string{
			"Enabled",
			"Suspended",
		},
	}
}

// Name returns the rule name
func (r *AwsS3BucketInvalidAccelerationStatusRule) Name() string {
	return "aws_s3_bucket_invalid_acceleration_status"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsS3BucketInvalidAccelerationStatusRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsS3BucketInvalidAccelerationStatusRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsS3BucketInvalidAccelerationStatusRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsS3BucketInvalidAccelerationStatusRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func (val string) error {
			found := false
			for _, item := range r.enum {
				if item == val {
					found = true
				}
			}
			if !found {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" is an invalid value as acceleration_status`, truncateLongMessage(val)),
					attribute.Expr.Range(),
				)
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
