// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"regexp"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule checks the pattern is valid
type AwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	max           int
	pattern       *regexp.Regexp
}

// NewAwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule returns new rule with default attributes
func NewAwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule() *AwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule {
	return &AwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule{
		resourceType:  "aws_sagemaker_model_package_group",
		attributeName: "model_package_group_description",
		max:           1024,
		pattern:       regexp.MustCompile(`^[\p{L}\p{M}\p{Z}\p{S}\p{N}\p{P}]*$`),
	}
}

// Name returns the rule name
func (r *AwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule) Name() string {
	return "aws_sagemaker_model_package_group_invalid_model_package_group_description"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsSagemakerModelPackageGroupInvalidModelPackageGroupDescriptionRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func (val string) error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"model_package_group_description must be 1024 characters or less",
					attribute.Expr.Range(),
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[\p{L}\p{M}\p{Z}\p{S}\p{N}\p{P}]*$`),
					attribute.Expr.Range(),
				)
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
