// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"log"
	"regexp"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsCodeartifactRepositoryInvalidRepositoryRule checks the pattern is valid
type AwsCodeartifactRepositoryInvalidRepositoryRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	max           int
	min           int
	pattern       *regexp.Regexp
}

// NewAwsCodeartifactRepositoryInvalidRepositoryRule returns new rule with default attributes
func NewAwsCodeartifactRepositoryInvalidRepositoryRule() *AwsCodeartifactRepositoryInvalidRepositoryRule {
	return &AwsCodeartifactRepositoryInvalidRepositoryRule{
		resourceType:  "aws_codeartifact_repository",
		attributeName: "repository",
		max:           100,
		min:           2,
		pattern:       regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._\-]{1,99}$`),
	}
}

// Name returns the rule name
func (r *AwsCodeartifactRepositoryInvalidRepositoryRule) Name() string {
	return "aws_codeartifact_repository_invalid_repository"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsCodeartifactRepositoryInvalidRepositoryRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsCodeartifactRepositoryInvalidRepositoryRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsCodeartifactRepositoryInvalidRepositoryRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsCodeartifactRepositoryInvalidRepositoryRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"repository must be 100 characters or less",
					attribute.Expr.Range(),
				)
			}
			if len(val) < r.min {
				runner.EmitIssue(
					r,
					"repository must be 2 characters or higher",
					attribute.Expr.Range(),
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					fmt.Sprintf(`"%s" does not match valid pattern %s`, truncateLongMessage(val), `^[A-Za-z0-9][A-Za-z0-9._\-]{1,99}$`),
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
