// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"
	"regexp"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsFsxOntapFileSystemInvalidFsxAdminPasswordRule checks the pattern is valid
type AwsFsxOntapFileSystemInvalidFsxAdminPasswordRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	max           int
	min           int
	pattern       *regexp.Regexp
}

// NewAwsFsxOntapFileSystemInvalidFsxAdminPasswordRule returns new rule with default attributes
func NewAwsFsxOntapFileSystemInvalidFsxAdminPasswordRule() *AwsFsxOntapFileSystemInvalidFsxAdminPasswordRule {
	return &AwsFsxOntapFileSystemInvalidFsxAdminPasswordRule{
		resourceType:  "aws_fsx_ontap_file_system",
		attributeName: "fsx_admin_password",
		max:           50,
		min:           8,
		pattern:       regexp.MustCompile(`^[^\x{0000}\x{0085}\x{2028}\x{2029}\r\n]{8,50}$`),
	}
}

// Name returns the rule name
func (r *AwsFsxOntapFileSystemInvalidFsxAdminPasswordRule) Name() string {
	return "aws_fsx_ontap_file_system_invalid_fsx_admin_password"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsFsxOntapFileSystemInvalidFsxAdminPasswordRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsFsxOntapFileSystemInvalidFsxAdminPasswordRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsFsxOntapFileSystemInvalidFsxAdminPasswordRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsFsxOntapFileSystemInvalidFsxAdminPasswordRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"fsx_admin_password must be 50 characters or less",
					attribute.Expr.Range(),
				)
			}
			if len(val) < r.min {
				runner.EmitIssue(
					r,
					"fsx_admin_password must be 8 characters or higher",
					attribute.Expr.Range(),
				)
			}
			if !r.pattern.MatchString(val) {
				runner.EmitIssue(
					r,
					`fsx_admin_password does not match valid pattern ^[^\x{0000}\x{0085}\x{2028}\x{2029}\r\n]{8,50}$`,
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
