// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"log"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule checks the pattern is valid
type AwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	max           int
	min           int
}

// NewAwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule returns new rule with default attributes
func NewAwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule() *AwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule {
	return &AwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule{
		resourceType:  "aws_amplify_backend_environment",
		attributeName: "deployment_artifacts",
		max:           1000,
		min:           1,
	}
}

// Name returns the rule name
func (r *AwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule) Name() string {
	return "aws_amplify_backend_environment_invalid_deployment_artifacts"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsAmplifyBackendEnvironmentInvalidDeploymentArtifactsRule) Check(runner tflint.Runner) error {
	log.Printf("[TRACE] Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		var val string
		err := runner.EvaluateExpr(attribute.Expr, &val, nil)

		err = runner.EnsureNoError(err, func() error {
			if len(val) > r.max {
				runner.EmitIssue(
					r,
					"deployment_artifacts must be 1000 characters or less",
					attribute.Expr.Range(),
				)
			}
			if len(val) < r.min {
				runner.EmitIssue(
					r,
					"deployment_artifacts must be 1 characters or higher",
					attribute.Expr.Range(),
				)
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	return nil
}
