// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsMskClusterInvalidBrokerNodeGroupInfoRule checks the pattern is valid
type AwsMskClusterInvalidBrokerNodeGroupInfoRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	valueMax      int
	valueMin      int
}

// NewAwsMskClusterInvalidBrokerNodeGroupInfoRule returns new rule with default attributes
func NewAwsMskClusterInvalidBrokerNodeGroupInfoRule() *AwsMskClusterInvalidBrokerNodeGroupInfoRule {
	return &AwsMskClusterInvalidBrokerNodeGroupInfoRule{
		resourceType:  "aws_msk_cluster",
		attributeName: "broker_node_group_info",
		valueMax:      32,
		valueMin:      5,
	}
}

// Name returns the rule name
func (r *AwsMskClusterInvalidBrokerNodeGroupInfoRule) Name() string {
	return "aws_msk_cluster_invalid_broker_node_group_info"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsMskClusterInvalidBrokerNodeGroupInfoRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsMskClusterInvalidBrokerNodeGroupInfoRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsMskClusterInvalidBrokerNodeGroupInfoRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsMskClusterInvalidBrokerNodeGroupInfoRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val map[string]string) error {
			for k, v := range val {
				if len(v) > r.valueMax {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag value for key %q must be 32 characters or less", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
				if len(v) < r.valueMin {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag value for key %q must be 5 characters or higher", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
