// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"fmt"
	"regexp"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/logger"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// AwsDxConnectionInvalidTagsRule checks the pattern is valid
type AwsDxConnectionInvalidTagsRule struct {
	tflint.DefaultRule

	resourceType  string
	attributeName string
	keyMax        int
	keyMin        int
	keyPattern    *regexp.Regexp
	valueMax      int
	valuePattern  *regexp.Regexp
}

// NewAwsDxConnectionInvalidTagsRule returns new rule with default attributes
func NewAwsDxConnectionInvalidTagsRule() *AwsDxConnectionInvalidTagsRule {
	return &AwsDxConnectionInvalidTagsRule{
		resourceType:  "aws_dx_connection",
		attributeName: "tags",
		keyMax:        128,
		keyMin:        1,
		keyPattern:    regexp.MustCompile(`^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`),
		valueMax:      256,
		valuePattern:  regexp.MustCompile(`^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`),
	}
}

// Name returns the rule name
func (r *AwsDxConnectionInvalidTagsRule) Name() string {
	return "aws_dx_connection_invalid_tags"
}

// Enabled returns whether the rule is enabled by default
func (r *AwsDxConnectionInvalidTagsRule) Enabled() bool {
	return true
}

// Severity returns the rule severity
func (r *AwsDxConnectionInvalidTagsRule) Severity() tflint.Severity {
	return tflint.ERROR
}

// Link returns the rule reference link
func (r *AwsDxConnectionInvalidTagsRule) Link() string {
	return ""
}

// Check checks the pattern is valid
func (r *AwsDxConnectionInvalidTagsRule) Check(runner tflint.Runner) error {
	logger.Trace("Check `%s` rule", r.Name())

	resources, err := runner.GetResourceContent(r.resourceType, &hclext.BodySchema{
		Attributes: []hclext.AttributeSchema{
			{Name: r.attributeName},
		},
	}, nil)
	if err != nil {
		return err
	}

	for _, resource := range resources.Blocks {
		attribute, exists := resource.Body.Attributes[r.attributeName]
		if !exists {
			continue
		}

		err := runner.EvaluateExpr(attribute.Expr, func(val map[string]string) error {
			for k, v := range val {
				if len(k) > r.keyMax {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag key %q must be 128 characters or less", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
				if len(k) < r.keyMin {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag key %q must be 1 characters or higher", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
				if !r.keyPattern.MatchString(k) {
					runner.EmitIssue(
						r,
						fmt.Sprintf(`tag key %q does not match valid pattern %s`, truncateLongMessage(k), `^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`),
						attribute.Expr.Range(),
					)
				}
				if len(v) > r.valueMax {
					runner.EmitIssue(
						r,
						fmt.Sprintf("tag value for key %q must be 256 characters or less", truncateLongMessage(k)),
						attribute.Expr.Range(),
					)
				}
				if !r.valuePattern.MatchString(v) {
					runner.EmitIssue(
						r,
						fmt.Sprintf(`tag value %q for key %q does not match valid pattern %s`, truncateLongMessage(v), truncateLongMessage(k), `^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$`),
						attribute.Expr.Range(),
					)
				}
			}
			return nil
		}, nil)
		if err != nil {
			return err
		}
	}

	return nil
}
