// This file generated by `generator/`. DO NOT EDIT

package models

import (
	"testing"
	"fmt"

	"github.com/terraform-linters/tflint-plugin-sdk/helper"
)

func Test_AwsLbInvalidIPAddressTypeRule(t *testing.T) {
	cases := []struct {
		Name     string
		Content  string
		Expected helper.Issues
	}{
		{
			Name: "It includes invalid characters",
			Content: `
resource "aws_lb" "foo" {
	ip_address_type = "ipv6"
}`,
			Expected: helper.Issues{
				{
					Rule:    NewAwsLbInvalidIPAddressTypeRule(),
					Message: fmt.Sprintf(`"%s" is an invalid value as %s`, truncateLongMessage("ipv6"), "ip_address_type"),
				},
			},
		},
		{
			Name: "It is valid",
			Content: `
resource "aws_lb" "foo" {
	ip_address_type = "ipv4"
}`,
			Expected: helper.Issues{},
		},
	}

	rule := NewAwsLbInvalidIPAddressTypeRule()

	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"resource.tf": tc.Content})

		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}

		helper.AssertIssuesWithoutRange(t, tc.Expected, runner.Issues)
	}
}
