package rules

import "github.com/terraform-linters/tflint-plugin-sdk/hclext"

// routeTargetAttributes is the set of mutually-exclusive routing target
// arguments of an aws_route resource. AWS requires exactly one of these to be
// set. It is shared by
//
// 1. aws_route_not_specified_target (errors when none is set)
// 2. aws_route_specified_multiple_targets (errors when more than one is set)
//
// The two rules validate against an identical set so they cannot drift apart.
var routeTargetAttributes = []hclext.AttributeSchema{
	{Name: "gateway_id"},
	{Name: "egress_only_gateway_id"},
	{Name: "nat_gateway_id"},
	{Name: "instance_id"},
	{Name: "vpc_peering_connection_id"},
	{Name: "network_interface_id"},
	{Name: "transit_gateway_id"},
	{Name: "vpc_endpoint_id"},
	{Name: "carrier_gateway_id"},
	{Name: "local_gateway_id"},
	{Name: "core_network_arn"},
	{Name: "odb_network_arn"},
}

var validElastiCacheNodeTypes = map[string]bool{
	// https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.SupportedTypes.html
	"cache.t2.micro":      true,
	"cache.t2.small":      true,
	"cache.t2.medium":     true,
	"cache.t3.micro":      true,
	"cache.t3.small":      true,
	"cache.t3.medium":     true,
	"cache.t4g.micro":     true,
	"cache.t4g.small":     true,
	"cache.t4g.medium":    true,
	"cache.m3.medium":     true,
	"cache.m3.large":      true,
	"cache.m3.xlarge":     true,
	"cache.m3.2xlarge":    true,
	"cache.m4.large":      true,
	"cache.m4.xlarge":     true,
	"cache.m4.2xlarge":    true,
	"cache.m4.4xlarge":    true,
	"cache.m4.10xlarge":   true,
	"cache.m5.large":      true,
	"cache.m5.xlarge":     true,
	"cache.m5.2xlarge":    true,
	"cache.m5.4xlarge":    true,
	"cache.m5.12xlarge":   true,
	"cache.m5.24xlarge":   true,
	"cache.m6g.large":     true,
	"cache.m6g.xlarge":    true,
	"cache.m6g.2xlarge":   true,
	"cache.m6g.4xlarge":   true,
	"cache.m6g.8xlarge":   true,
	"cache.m6g.12xlarge":  true,
	"cache.m6g.16xlarge":  true,
	"cache.m7g.large":     true,
	"cache.m7g.xlarge":    true,
	"cache.m7g.2xlarge":   true,
	"cache.m7g.4xlarge":   true,
	"cache.m7g.8xlarge":   true,
	"cache.m7g.12xlarge":  true,
	"cache.m7g.16xlarge":  true,
	"cache.r3.large":      true,
	"cache.r3.xlarge":     true,
	"cache.r3.2xlarge":    true,
	"cache.r3.4xlarge":    true,
	"cache.r3.8xlarge":    true,
	"cache.r4.large":      true,
	"cache.r4.xlarge":     true,
	"cache.r4.2xlarge":    true,
	"cache.r4.4xlarge":    true,
	"cache.r4.8xlarge":    true,
	"cache.r4.16xlarge":   true,
	"cache.r5.large":      true,
	"cache.r5.xlarge":     true,
	"cache.r5.2xlarge":    true,
	"cache.r5.4xlarge":    true,
	"cache.r5.12xlarge":   true,
	"cache.r5.24xlarge":   true,
	"cache.r6g.large":     true,
	"cache.r6g.xlarge":    true,
	"cache.r6g.2xlarge":   true,
	"cache.r6g.4xlarge":   true,
	"cache.r6g.8xlarge":   true,
	"cache.r6g.12xlarge":  true,
	"cache.r6g.16xlarge":  true,
	"cache.r6gd.large":    true,
	"cache.r6gd.xlarge":   true,
	"cache.r6gd.2xlarge":  true,
	"cache.r6gd.4xlarge":  true,
	"cache.r6gd.8xlarge":  true,
	"cache.r6gd.12xlarge": true,
	"cache.r6gd.16xlarge": true,
	"cache.r7g.large":     true,
	"cache.r7g.xlarge":    true,
	"cache.r7g.2xlarge":   true,
	"cache.r7g.4xlarge":   true,
	"cache.r7g.8xlarge":   true,
	"cache.r7g.12xlarge":  true,
	"cache.r7g.16xlarge":  true,
	"cache.c7gn.large":    true,
	"cache.c7gn.xlarge":   true,
	"cache.c7gn.2xlarge":  true,
	"cache.c7gn.4xlarge":  true,
	"cache.c7gn.8xlarge":  true,
	"cache.c7gn.12xlarge": true,
	"cache.c7gn.16xlarge": true,
	"cache.m1.small":      true,
	"cache.m1.medium":     true,
	"cache.m1.large":      true,
	"cache.m1.xlarge":     true,
	"cache.m2.xlarge":     true,
	"cache.m2.2xlarge":    true,
	"cache.m2.4xlarge":    true,
	"cache.c1.xlarge":     true,
	"cache.t1.micro":      true,
}

var previousElastiCacheNodeTypes = map[string]bool{
	// https://aws.amazon.com/elasticache/previous-generation/?nc1=h_ls
	"c1": true,
	"m1": true,
	"m2": true,
	"m3": true,
	"r3": true,
	"t1": true,
}
